[SystemParameter]
RAMLength            = 1024	      ;RAM空间长度(k)
VoltageBase          = 5000
ADBits               = 18
ADBase               = 8388608            ;AD分辨率
SaveType             = 2 ;保存类型 short - 0 float - 1 int - 2（新软件新添加的参数）
ContinueMaxFreq      = 512000
MaxFreq              = 512000
AllowFreqMode        = 3
AutoCheck            = 1
ExistSignalExtraTrig = 0
ExistExtraTrig       = 1
SoftExtraTrigInstant = 1
SendTrigCode         = 0
DetectAmplifier      = 0     ;是否自动检测放大器 0-设置 1-检测
SameFrequency        = 1
;连续与瞬态公用频率信息
OutClkCoordXCoef     = 1
;外部时钟横坐标修正系数
OutClkPntsPerCycle   = 2880 ;外部时钟模式下的周期点数
GPS                  = 0
CAN                  = 0
ExistIO              = 0
PulseCounter         = 0
PulseCounterCount    = 2
ExtraSpeed0          = 0 ;控制卡附加转速模式
ExtraSpeedCount      = 2
;控制卡存在几个转速通道
SplitSpeedCount      = 1
;一个转速通道分几路数据，不大于8
ExtraSignal0         = 0 ;控制卡信号源模式
ExtraSignalCount     = 2 ;控制卡存在几个信号源通道
SplitSignalCount     = 1 ;一个信号源通道分几路数据
OutDebugInfo         = 0;       输出调试信息
OutControlEnable     = 1 ;  外部网络连接控制
[TriggerParameter]
TriggerLevelCount = 10
TriggerLevel0     = 10%
TriggerLevel1     = 20%
TriggerLevel2     = 30%
TriggerLevel3     = 40%
TriggerLevel4     = 50%
TriggerLevel5     = 60%
TriggerLevel6     = 70%
TriggerLevel7     = 80%
TriggerLevel8     = 90%
TriggerLevel9     = OFF
[ContinuousSampleFrequency]
FrequencyLevelCount = 15
DefaultFreqIndex    = 9
Frequency0          = 10Hz,  12.8Hz
Frequency1          = 20Hz,  25.6Hz
Frequency2          = 50Hz,  51.2Hz
Frequency3          = 100Hz,   128Hz
Frequency4          = 200Hz,   256Hz
Frequency5          = 500Hz,   512Hz
Frequency6          = 1000Hz,  1280Hz
Frequency7          = 2000Hz,  2560Hz
Frequency8          = 5000Hz,  5120Hz
Frequency9          = 10000Hz, 12800Hz
Frequency10         = 20000Hz, 25600Hz
Frequency11         = 50000Hz, 51200Hz
Frequency12         = 100000Hz,128000Hz
Frequency13         = 200000Hz,256000Hz
Frequency14         = 500000Hz,512000Hz
ParaCode0           = 3,102
ParaCode1           = 4,103
ParaCode2           = 5,104
ParaCode3           = 6,105
ParaCode4           = 7,106
ParaCode5           = 8,107
ParaCode6           = 9,108
ParaCode7           = 10,109
ParaCode8           = 11,110
ParaCode9           = 12,111
ParaCode10          = 13,112
ParaCode11          = 14,113
ParaCode12          = 15,114
ParaCode13          = 16,116
ParaCode14          = 17,117
CtrlCode0           = 5, 3
CtrlCode1           = 5, 3
CtrlCode2           = 5, 3
CtrlCode3           = 5, 3
CtrlCode4           = 5, 3
CtrlCode5           = 4, 3
CtrlCode6           = 4, 3
CtrlCode7           = 4, 3
CtrlCode8           = 4, 3
CtrlCode9           = 4, 3
CtrlCode10          = 4, 3
CtrlCode11          = 4, 3
CtrlCode12          = 4, 3
CtrlCode13          = 4, 3
CtrlCode14          = 4, 3
NetJumpBlock0       = 1
NetJumpBlock1       = 1
NetJumpBlock2       = 1
NetJumpBlock3       = 1
NetJumpBlock4       = 1
NetJumpBlock5       = 1
NetJumpBlock6       = 1
NetJumpBlock7       = 2
NetJumpBlock8       = 4
NetJumpBlock9       = 8
NetJumpBlock10      = 16
NetJumpBlock11      = 32
NetJumpBlock12      = 64
NetJumpBlock13      = 128
NetJumpBlock14      = 256
DataRatio0          = 1
DataRatio1          = 1
DataRatio2          = 1
DataRatio3          = 1
DataRatio4          = 1
DataRatio5          = 2
DataRatio6          = 4
DataRatio7          = 16
DataRatio8          = 32
DataRatio9          = 64
DataRatio10         = 200
DataRatio11         = 512
DataRatio12         = 512
DataRatio13         = 512
DataRatio14         = 512
SectionNumber       = 6
SectionChannel0     = 64
SectionChannel1     = 32
SectionChannel2     = 16
SectionChannel3     = 8
SectionChannel4     = 4
SectionChannel5     = 1
SectionFrequency0   = 14
SectionFrequency1   = 14
SectionFrequency2   = 14
SectionFrequency3   = 14
SectionFrequency4   = 15
SectionFrequency5   = 15
[InstantSampleFrequency]
FrequencyLevelCount                                 = 14
DefaultFreqIndex                                    = 9
Frequency0                                          = 10Hz,  12.8Hz
Frequency1                                          = 20Hz,  25.6Hz
Frequency2                                          = 50Hz,  51.2Hz
Frequency3                                          = 100Hz,   128Hz
Frequency4                                          = 200Hz,   256Hz
Frequency5                                          = 500Hz,   512Hz
Frequency6                                          = 1000Hz,  1280Hz
Frequency7                                          = 2000Hz,  2560Hz
Frequency8                                          = 5000Hz,  5120Hz
Frequency9                                          = 10000Hz, 12800Hz
Frequency10                                         = 20000Hz, 25600Hz
Frequency11                                         = 50000Hz, 51200Hz
Frequency12                                         = 100000Hz,128000Hz
Frequency13                                         = 200000Hz,256000Hz
ParaCode0                                           = 3,102
ParaCode1                                           = 4,103
ParaCode2                                           = 5,104
ParaCode3                                           = 6,105
ParaCode4                                           = 7,106
ParaCode5                                           = 8,107
ParaCode6                                           = 9,108
ParaCode7                                           = 10,109
ParaCode8                                           = 11,110
ParaCode9                                           = 12,111
ParaCode10                                          = 13,112
ParaCode11                                          = 14,113
ParaCode12                                          = 15,114
ParaCode13                                          = 16,116
CtrlCode0                                           = 4
CtrlCode1                                           = 4
CtrlCode2                                           = 4
CtrlCode3                                           = 4
CtrlCode4                                           = 4
CtrlCode5                                           = 4
CtrlCode6                                           = 4
CtrlCode7                                           = 4
CtrlCode8                                           = 4
CtrlCode9                                           = 4
CtrlCode10                                          = 4
CtrlCode11                                          = 4
CtrlCode12                                          = 4
CtrlCode13                                          = 4

[InputModeItem]
InputModeCount								                                                   = 5
InputMode0									                                                      = DIF_DC,ParaCode=001
InputMode1									                                                      = SIN_DC,ParaCode=002
InputMode2									                                                      = AC,ParaCode=003
InputMode3									                                                      = IEPE,ParaCode=004
InputMode4										                                                  = GND,ParaCode=005

[Experiment]
;实验类型
;实验名称和使用电路,格式：前后都有','，以','分隔
Circuit0=,2,3,8,10,5,6,1,4,0,13,15,16,17,33,63,
;Circle Voltammetry(Single)
;Circle Voltammetry(Multiple Cycles)
;Chronoamperonetry
;Chronopotentiometry
;Chronocoulometry
;Staircase_Cyclic_Voltammetry_Single
;Linear_Scan_Voltammetry
;Staircase_Linear_Scan_Voltammetry
Circuit1=,9,14,34,64,

;自动电流档位
AutoCurrent = ,9,64,

;丢点数 DataThrowID为实验类型
DataThrow0=0

[Circuit]
;电路选项
CircuitCount=2
Circuit0=0	
;恒压源电路
Circuit1=1	
;恒流源电路
[ADSwitch]
;根据采样频率AD切换
ADSwitchFreq=0Hz
;// 采样频率分界线 接AD18bit/接AD24bit 200及以下采样频率为24位AD,Index=0 200以上采样频率为18位AD,Index=1
;new version 中只有1个AD。18bit
;ADSwitchCount=2
;ADSwitch0=0
;接AD24bit
;ADSwitch1=1
;接AD18bit
[ElectrolyticCellType]
;电解池选项
ElectrolyticCellTypeCount=2
ElectrolyticCellType0=0
;外部电解池
ElectrolyticCellType1=1
;内部电解池

[ElectrolyticCellOnOff]
;电解池开关选项
ElectrolyticCellOnOffCount=2
ElectrolyticCellOnOff0=0
;关
ElectrolyticCellOnOff1=1
;开

[Electrode]
;电极选项
ElectrodeCount=2
Electrode0=0
;三电极
Electrode1=1
;四电极
[ECPolarity]
;极性选项
ECPolarityCount=2
ECPolarity0=0
;正极性
ECPolarity1=1
;负极性
[ECReactive]
;正反馈选项
ECReactiveCount=2
ECReactive0=0
;关
ECReactive1=1
;开
;负反馈选项

[WaveParameter]
Level=3
Level0=1e-4
Level1=1
Level2=1e4
ConstFreq0=1e-3
ConstFreq1=1e3
ConstFreq2=1e5
ConstFreq3=5.12e7

;警告以下通道类型的编号与软件内部相关，不可随意调整
;数采通道1                                         
[AcquisitionChannelType1]
ChannelName                                                          = DH_AD0
;电压(采R极电势)
AcqTypeID                                                            = 001
FullValueCount                                                       = 1
FullValue0=10000mV,ParaCode=001
FilterUpCount                                                        = 6
FilterUpDefault                                                      = 5
FilterUp0                                                            = 10Hz, ParaCode=008
FilterUp1                                                            = 100Hz, ParaCode=006
FilterUp2                                                            = 1kHz, ParaCode=004
FilterUp3                                                            = 10kHz, ParaCode=002
FilterUp4                                                            = 100kHz, ParaCode=013
FilterUp5                                                            = PASS, ParaCode=001

ElectrodeCount = 2
Electrode0=0, ParaCode=000
Electrode1=1, ParaCode=001

ECReactiveCount = 2
ECReactive0=0, ParaCode=000
ECReactive1=1, ParaCode=001

ECCircuitCount = 2
ECCircuit0=0, ParaCode=000
ECCircuit1=1, ParaCode=001

ElectrolyticCellTypeCount = 2
ElectrolyticCellType0=0, ParaCode=001
ElectrolyticCellType1=1, ParaCode=000

ElectrolyticCellOnOffCount = 3
ElectrolyticCellOnOff0=0, ParaCode=000
ElectrolyticCellOnOff1=1, ParaCode=001
ElectrolyticCellOnOff2=2, ParaCode=002

CircuitFullValueCount = 1
CircuitFullValue0 = 10000mV,ParaCode=000

[AcquisitionChannelType2]
ChannelName                                                          = DH_AD1
;电流(恒压源实验采W极输出的电流，恒流源实验采C极输出的电流)
AcqTypeID                                                            = 002
FullValueCount                                                       = 10
FullValue0=2000mA,ParaCode=001
FullValue1=200mA,ParaCode=002
FullValue2=20mA,ParaCode=003
FullValue3=2mA,ParaCode=004
FullValue4=0.2mA,ParaCode=005
FullValue5=0.02mA,ParaCode=006
FullValue6=0.002mA,ParaCode=007
FullValue7=0.0002mA,ParaCode=008
FullValue8=0.00002mA,ParaCode=009
FullValue9=0.000004mA,ParaCode=010
FilterUpCount                                                        = 6
FilterUpDefault                                                      = 5
FilterUp0                                                            = 10Hz, ParaCode=008
FilterUp1                                                            = 100Hz, ParaCode=006
FilterUp2                                                            = 1kHz, ParaCode=004
FilterUp3                                                            = 10kHz, ParaCode=002
FilterUp4                                                            = 100kHz, ParaCode=013
FilterUp5                                                            = PASS, ParaCode=001
ECCircuitCount = 2
ECCircuit0=0, ParaCode=000
ECCircuit1=1, ParaCode=001
CircuitFullValueCount = 20
CircuitFullValue0 = 2000mA,ParaCode=009
CircuitFullValue1 = 200mA,ParaCode=008
CircuitFullValue2 = 20mA,ParaCode=007
CircuitFullValue3 = 2mA,ParaCode=006
CircuitFullValue4 = 0.2mA,ParaCode=005
CircuitFullValue5 = 0.02mA,ParaCode=004
CircuitFullValue6 = 0.002mA,ParaCode=003
CircuitFullValue7 = 0.0002mA,ParaCode=002
CircuitFullValue8 = 0.00002mA,ParaCode=001
CircuitFullValue9 = 0.000004mA,ParaCode=000
CircuitFullValue10 = 2000mA,ParaCode=041
CircuitFullValue11 = 200mA,ParaCode=040
CircuitFullValue12 = 20mA,ParaCode=039
CircuitFullValue13 = 2mA,ParaCode=038
CircuitFullValue14 = 0.2mA,ParaCode=037
CircuitFullValue15 = 0.02mA,ParaCode=036
CircuitFullValue16 = 0.002mA,ParaCode=035
CircuitFullValue17 = 0.0002mA,ParaCode=034
CircuitFullValue18 = 0.00002mA,ParaCode=033
CircuitFullValue19 = 0.000004mA,ParaCode=032

[AcquisitionChannelType3]
ChannelName                                                          = DH_SIGNAL
;信号源
AcqTypeID                                                            = 003
FilterUpCount                                                        = 6
FilterUpDefault                                                      = 5
FilterUp0                                                            = 10Hz, ParaCode=008
FilterUp1                                                            = 100Hz, ParaCode=006
FilterUp2                                                            = 1kHz, ParaCode=004
FilterUp3                                                            = 10kHz, ParaCode=002
FilterUp4                                                            = 100kHz, ParaCode=013
FilterUp5                                                            = PASS, ParaCode=001

[ChannelType0100]
ChannelName      = DH_VOLTAGE
MeasureSelCount  = 1  ; 测量内容项
MeasureSel0      = 80
FullValueCount   = 1
DefaultFullValue = 10
FullValue0       = 10000mV, AcqIndex= 0, AmpIndex = 0

[ChannelType0200]
ChannelName      = DH_CURRENT
MeasureSelCount  = 1  ; 测量内容项
MeasureSel0      = 79
FullValueCount   = 10
DefaultFullValue = 200000
FullValue0       = 2000mA, AcqIndex= 0, AmpIndex = 0
FullValue1       = 200mA, AcqIndex= 1, AmpIndex = 0
FullValue2       = 20mA, AcqIndex= 2, AmpIndex = 0
FullValue3       = 2mA, AcqIndex= 3, AmpIndex = 0
FullValue4       = 0.2mA, AcqIndex= 4, AmpIndex = 0
FullValue5       = 0.02mA, AcqIndex= 5, AmpIndex = 0
FullValue6       = 0.002mA, AcqIndex= 6, AmpIndex = 0
FullValue7       = 0.0002mA, AcqIndex= 7, AmpIndex = 0
FullValue8       = 0.00002mA, AcqIndex= 8, AmpIndex = 0
FullValue9       = 0.000004mA, AcqIndex= 9, AmpIndex = 0

CircuitType0_FullValueCount = 10
CircuitType0_FullValue0 = 2000mA, AcqIndex= 0, AmpIndex = 0
CircuitType0_FullValue1 = 200mA, AcqIndex= 1, AmpIndex = 0
CircuitType0_FullValue2 = 20mA, AcqIndex= 2, AmpIndex = 0
CircuitType0_FullValue3 = 2mA, AcqIndex= 3, AmpIndex = 0
CircuitType0_FullValue4 = 0.2mA, AcqIndex= 4, AmpIndex = 0
CircuitType0_FullValue5 = 0.02mA, AcqIndex= 5, AmpIndex = 0
CircuitType0_FullValue6 = 0.002mA, AcqIndex= 6, AmpIndex = 0
CircuitType0_FullValue7 = 0.0002mA, AcqIndex= 7, AmpIndex = 0
CircuitType0_FullValue8 = 0.00002mA, AcqIndex= 8, AmpIndex = 0
CircuitType0_FullValue9 = 0.000004mA, AcqIndex= 9, AmpIndex = 0
CircuitType1_FullValueCount = 10
CircuitType1_FullValue0 = 2000mA, AcqIndex= 10, AmpIndex = 0
CircuitType1_FullValue1 = 200mA, AcqIndex= 11, AmpIndex = 0
CircuitType1_FullValue2 = 20mA, AcqIndex= 12, AmpIndex = 0
CircuitType1_FullValue3 = 2mA, AcqIndex= 13, AmpIndex = 0
CircuitType1_FullValue4 = 0.2mA, AcqIndex= 14, AmpIndex = 0
CircuitType1_FullValue5 = 0.02mA, AcqIndex= 15, AmpIndex = 0
CircuitType1_FullValue6 = 0.002mA, AcqIndex= 16, AmpIndex = 0
CircuitType1_FullValue7 = 0.0002mA, AcqIndex= 17, AmpIndex = 0
CircuitType1_FullValue8 = 0.00002mA, AcqIndex= 18, AmpIndex = 0
CircuitType1_FullValue9 = 0.000004mA, AcqIndex= 19, AmpIndex = 0
CircuitType0_RCount = 0	;电阻计算
CircuitType1_RCount = 10
CircuitType1_R0 = 1
CircuitType1_R1 = 51
CircuitType1_R2 = 500
CircuitType1_R3 = 5000
CircuitType1_R4 = 50000
CircuitType1_R5 = 500000
CircuitType1_R6 = 5600000
CircuitType1_R7 = 50000000
CircuitType1_R8 = 620000000
CircuitType1_R9 = 2800000000


[ChannelType0300]
ChannelName      = DH_SIGNAL
MeasureSelCount  = 1  ; 测量内容项
MeasureSel0      = 81

[Channel]
ACQChannelTypeCount = 3 ;数采通道类型数
AMPChannelTypeCount = 0 ;适配器通道类型数


